### ISSUE TITLE
sendMessage to another id

### ISSUE THREAD

**Issue by uliaaan** [strikeentco/teabot#3]
Hi!
How sendMessage to another userId?
Dont see this params
`dialog.sendMessage(message, userId);`

**Comment by strikeentco** [comment]
Hi!

By default, in the dialog, you can only send a message to the initiator of the dialog.

But if, for some reason, in the dialog with current user you want send a message to another user, you can use internal `sendMessage` method which is inherited from `tg-yarl` package.

```javascript
TeaBot
  .defineCommand('/hello', (dialog, message) => {
    dialog.sendMessage('Hello!'); // send message to current user
    TeaBot.sendMessage(userId, 'Hello!'); // send message to another user
  });
```

You can find more info in the [docs](https://github.com/strikeentco/teabot/tree/master/docs).
